topp_tracker:
  sampling_frequency: 100
  n_gridpoints: 500
  request_permission: False

  constraints:

    velocity:
      x: 9
      y: 3
      z: 7
      yaw: 2.5

    acceleration:
      x: 4.75
      y: 3.75
      z: 3.75
      yaw: 1.5
